### ISSUE TITLE
Add ability to configure key-naming-convention rule

### ISSUE THREAD

**Issue by robertpatrick** [racodond/sonar-jproperties-plugin#78]
I have recently upgraded to the latest version of Sonarqube and the latest Sonar Java and Properties plugins.  While I understand the rational behind jproperties:key-naming-convention, our property based resource bundles follow a different key convention than what is available in the plugin.  I would like to see the plugin enhanced to allow me to customize the regular expression used by this rule to match our resource bundle key naming strategy.

**Comment by racodond** [comment]
Hi @robertpatrick,

The regular expression can be customized. Here's a screenshot:

![image](https://user-images.githubusercontent.com/1215713/35212027-15339328-ff59-11e7-9b0b-f74f50986c64.png)

Note that, with the latest version of SonarQube, built-in quality profiles cannot be changed. So maybe your issue is coming from there. In this case you should copy the built-in profile (SonarQube way), customize it and make it the default profile.

David

**Comment by robertpatrick** [comment]
My bad, I was looking at the rule in a "built-in" quality profile where that option doesn't appear.  By copying the built-in quality profile, I was able to edit it...sorry for the noise.

**Comment by racodond** [comment]
No problem!
